((nil . ((indent-tabs-mode . nil)
         (c-basic-offset . 4)
         (cmake-ide-build-dir . "~/code/github/nbd-3dge-debug")
         (compile-command . "cd ~/code/github/nbd-3dge-debug && cmake --build .")
         (projectile-project-compilation-cmd . "cd ~/code/github/nbd-3dge-debug && cmake --build .")
         (projectile-project-test-cmd . "cd ~/code/github/nbd-3dge-debug && ctest")
         (projectile-project-run-cmd . "cd ~/code/github/nbd-3dge-debug/bin && ./nbd-3dge")
         (projectile-test-suffix-function . (lambda (project-type) "_test"))
         ))
 (c-mode . ((mode . c++))))
