language: cpp

compiler:
  #- gcc
  - clang

cache:
  directories:
  - $HOME/.conan

python:
  - "3.4"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      #- g++-7
      - clang-5.0
      - libc++-dev
      - libc++abi-dev
      - python3-pip
      - libegl1-mesa-dev
      - libxcursor-dev
      - libxinerama-dev
      - libxi-dev
      - libxrandr-dev
      - libxss-dev
      - libasound2-dev
      - libjack-dev
      - libpulse-dev
      - libaudio-dev
      - unzip
    update: true

env:
  #- MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

git:
  lfs_skip_smudge: true

before_install:
  - eval "${MATRIX_EVAL}"
  
install:
  # Install conan
  - sudo pip3 install conan
  # Automatic detection of your arch, compiler, etc.
  - conan user
  - conan remote add -f bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - ./install-dependencies.py

script:
  - mkdir build && cd build
  - conan install .. --build=missing -s compiler=clang -s compiler.version=5.0 -s compiler.libcxx=libc++
  #-o sdl2:alsa=False -o sdl2:jack=False -o sdl2:pulse=False -o sdl2:nas=False -o sdl2:esd=False -o sdl2:arts=False -o sdl2:directfb=False -o sdl2:x11=False
  - cmake -DCMAKE_BUILD_TYPE=Release ../
  - make

