language: cpp

compiler:
  #- gcc
  - clang

cache:
  directories:
  - $HOME/.conan

python:
  - "3.4"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      #- g++-7
      - clang-5.0
      - libc++-dev
      - libc++abi-dev
    update: true

env:
  #- MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

git:
  lfs_skip_smudge: true

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get -y install python3-pip
  
install:
  # Install conan
  - sudo pip3 install conan
  # Automatic detection of your arch, compiler, etc.
  - conan user
  - conan remote add -f bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - sudo ./install-dependencies.sh

script:
  - mkdir build && cd build
  - conan install .. --build=missing -s compiler.libcxx=libstdc++11 -o sdl2:alsa=False -o sdl2:jack=False -o sdl2:pulse=False -o sdl2:nas=False -o sdl2:esd=False -o sdl2:arts=False
  - cmake -DCMAKE_BUILD_TYPE=Release ../
  - make

