language: cpp

compiler:
  - gcc

python:
  - "3.4"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
    update: true

env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

git:
  lfs_skip_smudge: true

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get -y install python3-pip
  
install:
  # Install conan
  - sudo pip3 install conan
  # Automatic detection of your arch, compiler, etc.
  - conan user
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - sudo ./install-dependencies.sh

script:
  - mkdir build && cd build
  - conan install .. --build=missing -s compiler.libcxx=libstdc++11
  - cmake -DCMAKE_BUILD_TYPE=Release ../
  - make

