language: cpp

compiler:
  - gcc
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
    update: true

env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

git:
  lfs_skip_smudge: true

before_install:
  - eval "${MATRIX_EVAL}"
  
install:
  - sudo ./install-dependencies.sh

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ../
  - make
