language: cpp

compiler:
  - gcc

python:
  - "3.6"
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
    update: true

env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

git:
  lfs_skip_smudge: true

before_install:
  - eval "${MATRIX_EVAL}"
  
install:
  # Install conan
  - pip install conan
  # Automatic detection of your arch, compiler, etc.
  - conan user
  - sudo ./install-dependencies.sh

script:
  - mkdir build && cd build
  - conan install .. --build=missing -s build_type=Release -s compiler.libcxx=libstdc++11
  - cmake -DCMAKE_BUILD_TYPE=Release ../
  - make
