version: 0.1.{build}
platform: x64

clone_script:
  - git lfs clone -q --exclude=data --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - git checkout -qf %APPVEYOR_REPO_COMMIT%

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: conan install .. --build=missing
  - cmd: cmake ../ -G "Visual Studio 14 2015 Win64"
  - cmd: cmake --build . --config Release
  - cmd: cd ..

test_script:
  - cmd: cd build
  - cmd: ctest
  - cmd: cd ..
